name: terraform
on:
  push:
  pull_request:

jobs:
  terraform:
      runs-on: ubuntu-latest

  defaults:
    working-directory: ./terraform/stage

  steps:
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.0

  - name: Terraform fmt
    id: fmt
    run: terraform fmt -check
    continue-on-error: true

  - name: Terraform Init
    id: init
    run: terraform init

  - name: Terraform Validate
    id: validate
    run: terraform validate -no-color
